
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
export const GET_USERS = "GET_USERS";
export const GETUSERS_FAIL = "GETUSERS_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_HOUSE = " GET_HOUSE";


export const GET_HOUSES = " GET_HOUSES";


export const UPDATE_HOUSE = "UPDATE_HOUSE";


export const DELETE_HOUSE = "DELETE_HOUSE";

export const ADD_HOUSE = "ADD_HOUSE";
export const HOUSE_ERROR = "HOUSE_ERROR";


export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'
export const EVENTS_CREATE_REVIEW_REQUEST = 'EVENTS_CREATE_REVIEW_REQUEST'
export const EVENTS_CREATE_REVIEW_SUCCESS = 'EVENTS_CREATE_REVIEW_SUCCESS'
export const EVENTS_CREATE_REVIEW_FAIL = 'EVENTS_CREATE_REVIEW_FAIL'
export const EVENTS_CREATE_REVIEW_RESET = 'EVENTS_CREATE_REVIEW_RESET'
export const EVENTS_REQUEST = 'EVENTS_REQUEST'
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS'
export const EVENTS_FAIL = 'EVENTS_FAIL'
export const DELETE_EVENT = "DELETE_EVENT"
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL"
